name: Deploy HostGator

# Aqui dizemos que a automação vai rodar "toda vez que houver um PUSH na branch MAIN"
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Enviar arquivos para a HostGator
    runs-on: ubuntu-latest
    steps:
      # Passo 1: O GitHub entra na sua pasta do repositório e lê seus arquivos
      - name: Pegar codigo do repositorio
        uses: actions/checkout@v4
      
      # Passo 2: O GitHub usa aquele robozinho do FTP para logar na HostGator e subir os arquivos
      - name: Sincronizar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /                         # <--- Altere para ficar exatamente assim, só a barra!
          port: 21
          security: loose